package incus

import (
	"bytes"
	"fmt"
	"os"
	"os/user"
	"strings"
	"text/template"
	"time"
)

const cloudInitTemplate = `#cloud-config
# Generated by igloo on {{.Timestamp}}

users:
  - name: {{.Username}}
    uid: {{.UID}}
    groups: sudo, video, render, audio
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true

timezone: {{.Timezone}}

runcmd:
  - mkdir -p /home/{{.Username}}
  - chown {{.UID}}:{{.GID}} /home/{{.Username}}
  - mkdir -p /run/user/{{.UID}}
  - chown {{.UID}}:{{.GID}} /run/user/{{.UID}}
  - chmod 700 /run/user/{{.UID}}
`

type cloudInitData struct {
	Username  string
	UID       int
	GID       int
	Timezone  string
	Timestamp string
}

// GenerateCloudInit creates a cloud-init config for user mapping and basic setup.
func GenerateCloudInit() (string, error) {
	currentUser, err := user.Current()
	if err != nil {
		return "", fmt.Errorf("failed to get current user: %w", err)
	}

	data := cloudInitData{
		Username:  currentUser.Username,
		UID:       os.Getuid(),
		GID:       os.Getgid(),
		Timezone:  getTimezone(),
		Timestamp: time.Now().Format(time.RFC3339),
	}

	tmpl, err := template.New("cloud-init").Parse(cloudInitTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse cloud-init template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute cloud-init template: %w", err)
	}

	return buf.String(), nil
}

func getTimezone() string {
	if data, err := os.ReadFile("/etc/timezone"); err == nil {
		return strings.TrimSpace(string(data))
	}
	if target, err := os.Readlink("/etc/localtime"); err == nil {
		parts := strings.Split(target, "/zoneinfo/")
		if len(parts) == 2 {
			return parts[1]
		}
	}
	if tz := os.Getenv("TZ"); tz != "" {
		return tz
	}
	return "UTC"
}
